import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import InputPrompt from "@/components/InputPrompt";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lucid Thoughts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*Header */}
        <Header />

        {/* Input Box */}
        <InputPrompt />
        {children}
      </body>
    </html>
  );
}
